# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Christofer Whitehead
title: Computer Science Student
email: chrisfromtheabyss@protonmail.com
website: chrisabyss.github.io

# Social links
# twitter_username:
github_username:  chrisabyss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Chris and I'm a student at North Virginia Community College, I have been attending since 16, and am currently duel-enrolled full time. I will receve a A.S. in Computer Science and a High School Diploma at the same time.
  I have always been passionate for both cybersecurity and FOSS, have exprence scripting, and am quite proficent at hardening personal computer systems, and engaging in good OPSEC for both security and privacy.

  I am most skilled in: <mark>Linux</mark> <mark>Python</mark> and <mark>Security</mark>

# Projects Section
# projects_title: Projects

# Education Section
educaton_title: Education

# Experience Section
experience_title: Experience

  # More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Art
   - [Photography](https://chrisabyss.github.io/photography/)
   - Phliosophy
   - Debate
   - Mountain Biking
   - Whitewater Kayaking
   - Canyoneering
   - Wilderness Exploration and Survival

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
